### PR TITLE
Update CI

### PR DESCRIPTION
**Pull request by Zehvogel**

### CODE REVIEW

**Comment by jmcarcell** [comment]
If you want I can add the key4hep builds here; if building with cmake works then it will run ctest. I add it to the obvious C++ packages but it's probably fine on other repos like this one

**Comment by Zehvogel** [comment]
It feels a bit overkill to add that for a package where nothing is actually built but I would be fine if it means that I will never have to touch it again :D

**Comment by jmcarcell** [comment]
There you go:
https://github.com/key4hep/CLDConfig/blob/main/.github/workflows/key4hep-build.yaml

**Comment by Zehvogel** [comment]
centos7 test failures are expected: https://github.com/key4hep/key4hep-spack/issues/558

**Pull request merged**
