### PR TITLE
Rework tests

### LINKED ISSUE #9: Add edm4hep input test
- [ ] Find better place for the test input files, e.g. key4hep eos
- [ ] Document how test input files are created
- [ ] Create edm4hep test input file
- [ ] Add test for edm4hep input

### PR DESCRIPTION
**Pull request by Zehvogel**
BEGINRELEASENOTES
- Add test for edm4hep input and create test inputs directly with ddsim

ENDRELEASENOTES

resolves #9

### CODE REVIEW

**Comment by andresailer** [comment]
We should have a dependency of the rec tests on the respective sim test?

**Comment by Zehvogel** [comment]
good idea

**Comment by Zehvogel** [comment]
urgh I did not get the warnings about `pytest.mark.dependency()` not being available on my machine and was hoping that we had it in the key4hep pytest install but looks like this is not the case :/ Then we will have to switch to some other test system if we want to have tests depend on each other I guess?

**Comment by andresailer** [comment]
I think using cmake/ctest would be fine.

**Comment by Zehvogel** [comment]
is there any way to set that up without requiring the for this project useless cmake/make step?

**Comment by andresailer** [comment]
What do you mean with useless cmake step? You create a CMakeLists.txt file and run cmake and then ctest?

**Pull request merged**
